### PR TITLE
Added tags to role dependencies.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by drybjed** [comment]
@ypid Thanks! What do you think about new tagging style anyway?

**Comment by ypid** [comment]
Quite nice I would say :+1: . Did you come up with this?

**Comment by drybjed** [comment]
Yes, I based it on Debian's [debtags](https://debtags.debian.net). It's probably a little more precise to use context-based tags with such a large playbook than generic role names as tags.

**Comment by ypid** [comment]
I agree. Nice work …

**Pull request merged**
